import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score
df = pd.read_csv('price1.csv', sep='\t')
df.columns = df.columns.str.strip()
for col in df.select_dtypes(include='object'):
    df[col] = df[col].map(lambda x: x.strip() if isinstance(x, str) else x)
df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
print(df.head())
print(df.describe())
plt.figure(figsize=(10, 6))
plt.hist(df['Price'], bins=15, edgecolor='black', color='skyblue')
plt.title('Car Price Distribution')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()
avg_price_by_make = df.groupby('Make')['Price'].mean().sort_values()
plt.figure(figsize=(12, 8))
avg_price_by_make.plot(kind='barh', color='orange')
plt.title('Average Car Price by Make')
plt.xlabel('Average Price')
plt.ylabel('Car Make')
plt.grid(True)
plt.show()
avg_price_by_year = df.groupby('Year')['Price'].mean()
plt.figure(figsize=(10, 6))
avg_price_by_year.plot(kind='line', marker='o', linestyle='--', color='green')
plt.title('Average Car Price by Year')
plt.xlabel('Year')
plt.ylabel('Average Price')
plt.grid(True)
plt.show()
X = pd.get_dummies(df[['Make', 'Model', 'Year']], drop_first=True)
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
rmse = root_mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("\n Model Evaluation:")
print("Root Mean Squared Error (RMSE):", round(rmse, 2))
print("R² Score:", round(r2, 2))
new_car = pd.DataFrame([{'Make': 'Honda', 'Model': 'Civic', 'Year': 2021}])
new_car_encoded = pd.get_dummies(new_car)
new_car_encoded = new_car_encoded.reindex(columns=X.columns, fill_value=0)
predicted_price = model.predict(new_car_encoded)
print("\n Predicted Price for Honda Civic (2021): $", round(predicted_price[0], 2))
